services:
  caddy:
    image: caddy:latest
    container_name: pdl-caddy
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ".env"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.5"
          memory: "256M"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - /wb/static:/wb/static:ro
    networks:
      - pdl-network
      - lexoterm-network
  mongodb:
    image: mongo:8
    container_name: pdl-mongodb
    env_file:
      - ".env"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pdl-network
      - lexoterm-network
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "2.5G"
        reservations:
          cpus: "1.5"
          memory: "2.5G"
  postgres:
    image: postgres:17
    container_name: pdl-postgres
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pdl-network
      - lexoterm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "1G"
  pdl-api:
    image: ghcr.io/pdl-lex/pdl-api:latest
    container_name: pdl-api
    env_file:
      - ".env"
    networks:
      - pdl-network
      - lexoterm-network
    depends_on:
      - mongodb
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=lexoterm-network
      - traefik.http.routers.pdl-api.rule=Host(`api.lexoterm.de`)
      - traefik.http.routers.pdl-api.entrypoints=websecure
      - traefik.http.routers.pdl-api.tls=true
      - traefik.http.services.pdl-api.loadbalancer.server.port=80
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--proxy-headers",
        "--port",
        "80",
      ]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2.5G"
        reservations:
          cpus: "2"
          memory: "2.5G"
  pdl-platform:
    image: ghcr.io/pdl-lex/pdl-platform:latest
    container_name: pdl-platform
    env_file:
      - ".env"
    networks:
      - pdl-network
      - lexoterm-network
    depends_on:
      - pdl-api
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=lexoterm-network
      - traefik.http.routers.pdl-platform.rule=Host(`ba00000-lex.srv.mwn.de`,`azlex.de`,`lexoterm.de`)
      - traefik.http.routers.pdl-platform.entrypoints=websecure
      - traefik.http.routers.pdl-platform.tls=true
      - traefik.http.services.pdl-platform.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "1G"
  pdl-cms:
    image: ghcr.io/pdl-lex/pdl-cms:latest
    container_name: pdl-cms
    depends_on:
      - mongodb
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URL=${MONGODB_URI}
      - ALLOWED_ORIGIN=${CMS_ALLOWED_ORIGIN}
    restart: unless-stopped
    volumes:
      - payload-media:/app/media
    networks:
      - pdl-network
      - lexoterm-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=lexoterm-network
      - traefik.http.routers.pdl-cms.rule=Host(`cms.lexoterm.de`)
      - traefik.http.routers.pdl-cms.entrypoints=websecure
      - traefik.http.routers.pdl-cms.tls=true
      - traefik.http.services.pdl-cms.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "512M"
  pdl-smor-api:
    image: ghcr.io/pdl-lex/smor-api:latest
    container_name: pdl-smor-api
    environment:
      - SMOR_DEMO_URL=${SMOR_DEMO_URL}
    networks:
      - pdl-network
      - lexoterm-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=lexoterm-network
      - traefik.http.routers.pdl-smor-api.rule=Host(`smor.lexoterm.de`)
      - traefik.http.routers.pdl-smor-api.entrypoints=websecure
      - traefik.http.routers.pdl-smor-api.tls=true
      - traefik.http.services.pdl-smor-api.loadbalancer.server.port=8000
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "4G"
        reservations:
          cpus: "0.25"
          memory: "1G"
  pdl-wbf-nlp-demo:
    image: ghcr.io/pdl-lex/wbf-nlp-demo:latest
    container_name: wbf-nlp-demo
    networks:
      - pdl-network
      - lexoterm-network
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=lexoterm-network
      - traefik.http.routers.wbf-nlp-demo.rule=Host(`wbfdemo.lexoterm.de`)
      - traefik.http.routers.wbf-nlp-demo.entrypoints=websecure
      - traefik.http.routers.wbf-nlp-demo.tls=true
      - traefik.http.services.wbf-nlp-demo.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "512M"
networks:
  pdl-network:
    driver: bridge
  lexoterm-network:
    external: true
volumes:
  caddy_data:
  caddy_config:
  mongodb_data:
  payload-media:
  postgres_data:
  