services:
  pdl-cms:
    image: ghcr.io/pdl-lex/pdl-cms:latest
    container_name: pdl-cms
    restart: unless-stopped
    volumes:
      - payload-media:/app/media
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "512M"
volumes:
  payload-media:
    name: pdl-deployment_payload-media